language: csharp
mono: latest
dotnet: 3.1
jobs:
  include:
    - stage: "Build"
      install: dotnet restore
      script: dotnet build
    - stage: "Generate Documentation"
      if: branch = master
      install:
        - dotnet restore
        - nuget install docfx.console  -Version $DOCFX_VERSION
      script:
        - mono ./docfx.console.$DOCFX_VERSION/tools/docfx.exe metadata docfx_project/docfx.json
        - mono ./docfx.console.$DOCFX_VERSION/tools/docfx.exe build docfx_project/docfx.json
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docfx_project/_site
        fqdn: gravyirc.halomademeapc.com
        on:
          branch: 
          - master
    - stage: "Run Tests"
      install: dotnet restore
      script: dotnet test tests/GravyIrc.Tests/GravyIrc.Tests.csproj --verbosity detailed
    - stage: "Publish to NuGet"
      if: branch = master
      install: dotnet restore
      script: 
        - dotnet build
        - dotnet publish -c release
        - dotnet pack -c release --include-symbols -o publish
        - for f in publish/*.nupkg ; do dotnet nuget push $f --skip-duplicate -k $NUGET_TOKEN ; done